sudo: false

language: node_js
node_js:
  - 14.6

branches:
  only:
    - master

deploy:
  provider: heroku
  app: "kresh-continuous-integration"
  api_key:
    secure: "6facb0fd-cc4d-4f33-85b4-2a3301fe2416"
