sudo: false

language: node_js
node_js:
  - 14.6

branches:
  only:
    - master

deploy:
  provider: heroku
  app: "continuous_integration"
  api_key:
    secure: "6f8ea26e-bced-43eb-8cd4-e41e4a0c91f2"

after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js